---
architecture: M1
cluster_name: p2d2_lab
cluster_tags: {}

keyring_backend: system
vault_name: df7de378-da1f-49f1-8e5a-cfb1702f2a35

cluster_rules:
- cidr_ip: <you_ip_here>/32
  from_port: 22
  proto: tcp
  to_port: 22
- cidr_ip: 10.33.34.224/28
  from_port: 0
  proto: tcp
  to_port: 65535
  # Allow connection to shellinabox
- cidr_ip: 0.0.0.0/0
  from_port: 443
  proto: tcp
  to_port: 443
  # Allow connection to http servers
- cidr_ip: 0.0.0.0/0
  from_port: 8000
  proto: tcp
  to_port: 8030
ec2_ami:
  Name: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20240228
  Owner: 099720109477
ec2_instance_reachability: public
ec2_vpc:
  eu-west-1:
    Name: p2d2
    cidr: 10.33.0.0/16

cluster_vars:
  failover_manager: repmgr
  postgres_flavour: postgresql
  postgres_version: '16'
  preferred_python_version: python3
  use_volatile_subscriptions: false
  packages:
    Ubuntu:
      - jq
      - git
      - shellinabox
      - python3-pip
  extra_postgres_packages:
    common:
      - postgresql-16-pgvector
  extra_postgres_extensions:
  - vector

locations:
- Name: main
  az: eu-west-1a
  region: eu-west-1
  subnet: 10.33.34.224/28

instance_defaults:
  default_volumes:
  - device_name: root
    encrypted: true
    volume_size: 32
    volume_type: gp2
  platform: aws
  type: t3.xlarge
  vars:
    ansible_user: ubuntu

instances:
- Name: p2d2lab01
  location: main
  node: 1
  role:
  - primary
  vars:
    published_ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
    postgres_users:
    - username: user01
    - username: user02
    - username: user03
    - username: user04
    - username: user05
    postgres_databases:
    - name: p2d2db01
      owner: user01
      extensions: []
    - name: p2d2db02
      owner: user02
      extensions: []
    - name: p2d2db03
      owner: user03
      extensions: []
    - name: p2d2db04
      owner: user04
      extensions: []
    - name: p2d2db05
      owner: user05
      extensions: []

- Name: p2d2lab02
  location: main
  node: 2
  role:
  - primary
  vars:
    published_ports:
      - "8006:8006"
      - "8007:8007"
      - "8008:8008"
      - "8009:8009"
      - "8010:8010"
    postgres_users:
    - username: user06
    - username: user07
    - username: user08
    - username: user09
    - username: user10
    postgres_databases:
    - name: p2d2db06
      owner: user06
      extensions: []
    - name: p2d2db07
      owner: user07
      extensions: []
    - name: p2d2db08
      owner: user08
      extensions: []
    - name: p2d2db09
      owner: user09
      extensions: []
    - name: p2d2db10
      owner: user10
      extensions: []

- Name: p2d2lab03
  location: main
  node: 3
  role:
  - primary
  vars:
    published_ports:
      - "8011:8011"
      - "8012:8012"
      - "8013:8013"
      - "8014:8014"
      - "8015:8015"
    postgres_users:
    - username: user11
    - username: user12
    - username: user13
    - username: user14
    - username: user15
    postgres_databases:
    - name: p2d2db11
      owner: user11
      extensions: []
    - name: p2d2db12
      owner: user12
      extensions: []
    - name: p2d2db13
      owner: user13
      extensions: []
    - name: p2d2db14
      owner: user14
      extensions: []
    - name: p2d2db15
      owner: user15
      extensions: []

- Name: p2d2lab04
  location: main
  node: 4
  role:
  - primary
  vars:
    published_ports:
      - "8016:8016"
      - "8017:8017"
      - "8018:8018"
      - "8019:8019"
      - "8020:8020"
    postgres_users:
    - username: user16
    - username: user17
    - username: user18
    - username: user19
    - username: user20
    postgres_databases:
    - name: p2d2db16
      owner: user16
      extensions: []
    - name: p2d2db17
      owner: user17
      extensions: []
    - name: p2d2db18
      owner: user18
      extensions: []
    - name: p2d2db19
      owner: user19
      extensions: []
    - name: p2d2db20
      owner: user20
      extensions: []

- Name: p2d2lab05
  location: main
  node: 5
  role:
  - primary
  vars:
    published_ports:
      - "8021:8021"
      - "8022:8022"
      - "8023:8023"
      - "8024:8024"
      - "8025:8025"
    postgres_users:
    - username: user21
    - username: user22
    - username: user23
    - username: user24
    - username: user25
    postgres_databases:
    - name: p2d2db21
      owner: user21
      extensions: []
    - name: p2d2db22
      owner: user22
      extensions: []
    - name: p2d2db23
      owner: user23
      extensions: []
    - name: p2d2db24
      owner: user24
      extensions: []
    - name: p2d2db25
      owner: user25
      extensions: []

- Name: p2d2dataset
  location: main
  node: 6
  role:
  - primary
  vars:
    type: t3.micro
    default_volumes:
    - device_name: root
      encrypted: true
      volume_size: 16
      volume_type: gp2
